
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

COPY .env ./

RUN npm install --legacy-peer-deps

RUN apk add --no-cache curl

COPY . .

RUN npm run build

ENV NODE_ENV=production

EXPOSE 3000

CMD ["node", "dist/main"]